#!/bin/bash

load test_helper/helper

setup(){
  if [ -d ~/tmp/git-gadgets-test ]; then
  find ~/tmp/git-gadgets-test -mindepth 1 -delete
  else
    mkdir -p ~/tmp/git-gadgets-test
  fi
  cd ~/tmp/git-gadgets-test && git init
  touch ~/tmp/focona
  [ -f foca ] || touch foca
  git add foca && git commit -m "First commit"
}

@test "[Bump] "
